apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: test
spec:
  replicas: 1
  selector:
   matchLabels:
    app: mysql
  template:
   metadata:
    labels:
     app: mysql
   spec:
    containers:
     - name: mysql
       image: mysql:8.0
       env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: testdb
       ports:
       - containerPort: 3306

